; Configuración de la sirena manual.

; Para ver los códigos de las letras entra enhttp://www.indigorose.com/webhelp/ams/Program_Reference/Misc/Virtual_Key_Codes.htm
; USAR LA TABLA "DECIMAL" A LA HORA DE ESCOGER UNA LETRA DE LA PÁGINA O NO FUNCIONARÁ.

[SIRENA]b
wail=66 ; B
yelp=67 ; C
test=0
