; Advanced Vehicle Sirens by Cake - do not remove these two lines
; https://forum.ls-rp.com/memberlist.php?mode=viewprofile&u=336216

[Keys]
KeyDelay=200

SirenState=R
SirenStateNumbers=true

SirenMute=L

SpotlightToggle=B

IndicatorClear=SHIFT
IndicatorLeft=Z
IndicatorBoth=X
IndicatorRight=C

Foglights=J

[Sirens]
Enabled=true
StreamDistance=260.0
DisableDefault=true

[SirenMute]
Enabled=true

[SirenFlares]
Enabled=false
Distance=30.0

[Indicators]
Enabled=true
Delay=500

[Foglights]
Enabled=true
EnableWithSiren=false

[Paintjobs]
Enabled=false

[Steering]
Enabled=false
CheckController=false

[Spotlights]
Enabled=false

[Helper]
ImVehFt=true

GameFocus=true

Multiplayer=true
MultiplayerMessages=true

LogMaterials=false
LogDummies=false

[Hiiiii]
Enabled=false
